title: Ruoqi Liu
position: Ph.D. Student
affiliation: The Ohio State University
email: liu.7324@osu.edu
keywords: Ruoqi Liu's homepage
google_scholar: https://scholar.google.com/citations?user=bScV4D0AAAAJ&hl=en
github_link: https://github.com/ruoqi-liu/
linkedin: https://www.linkedin.com/in/ruoqi-liu/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Ruoqi Liu's homepage.
canonical: https://ruoqi-liu.github.io/
remote_theme: ruoqi-liu/ruoqi-liu.github.io
